samples: ["SRR17138637","SRR17138639"]
in_path: "./raw_data/"
out_path: "./results/"

threads:
  normal: 16
  high: 60

flank_file: "./lib/fmr1_flanks.fa"
ref_path: "./lib/hg38_chrXY.fna"
iterations: 1 #3, racon 迭代次数

# FMR1 区域
chr: "NC_000023.11"
fmr1_start: 147912051
pad_bp: 50000